version: '3'

services:
  vision:
    build: .
    container_name: vision
    restart: unless-stopped
    volumes:
      - ./python-scripts:/opt/python-scripts/
      - ./trigger-scripts:/opt/trigger-scripts/
      - ./vision.cfg:/opt/vision.cfg
